### ISSUE TITLE
Give user the opportunity to "tell their story" as first interaction with Bot 

### ISSUE THREAD

**Issue by 0kSure** [HumanbiOS/telegram_bot_frontend#48]
- before disclaimer  
- limit to 400 signs

**Comment by Poolitzer** [comment]
> Give the opportunity

Sounds like you want this implemented as not required, do I understand this correctly? And can you give me an example of the bots question for their story and a possible their story answer? Also, what is supposed to happen with the story in the end?

**Comment by 0kSure** [comment]
I'd go like:
"Hello! Thank you for contacting Human Bios. Before we ask you a couple of diagnosis questions, take the opportunity to tell us your story, if you would like to.
 
Where are you right now? How are your friends, your family? Do you feel safe? 

We will forward what you tell us to the people that pick up your case." 

After that, new dialogue with a (small) skip option: 

"You can also take a picture of yourself right now and send it here. This will help other people to understand your situation."
