### ISSUE TITLE
Add button for worker to send link to video call

### ISSUE THREAD

**Issue by 0kSure** [HumanbiOS/telegram_bot_frontend#51]
call_id/Link has to be pulled from an API (Zoom, Hangout, whereby) and send to worker/user conversation 
See: 
 - https://developers.google.com/hangouts/chat/how-tos/rest-api
- https://marketplace.zoom.us/docs/api-reference/zoom-api/rooms/addaroom

**Comment by Poolitzer** [comment]
@0kSure for zoom, I think the correct API call is https://marketplace.zoom.us/docs/api-reference/zoom-api/meetings/meetingcreate
