### ISSUE TITLE
Provide guidelines to workers

### ISSUE THREAD

**Issue by d-Rickyy-b** [HumanbiOS/telegram_bot_frontend#7]
- Provide "how to calm someone down text" to workers that pick up social/psychological cases. Repeat after x cases
- Provide emergency heuristics to workers that pick up medical cases for the first time. Repeat after x cases
- Provide WHO recommendations to workers that pick up medical cases for the first time. Repeat after x cases.

**Comment by YuKitAs** [comment]
5474a2741721226ece430ecc1ce9f15809edc5de
